### ISSUE TITLE
Wrong Translation in adt.sql

### ISSUE THREAD

**Issue by kruedger** [lochmueller/static_info_tables_zh#13]
Hello,
there are 3 Errors in the Translation.sql
There is a '>,'P in the line and Pitcairn is not translated

**Comment by lochmueller** [comment]
Hey @kruedger 
which line do you mean? https://github.com/lochmueller/static_info_tables_zh/blob/master/ext_tables_static%2Badt.sql
I don't saw any errors?!?
Regards,
TIm

**Comment by lochmueller** [comment]
Pitcairn is currently not translated at all: https://github.com/lochmueller/static_info_tables_zh/blob/master/ext_tables_static%2Badt.sql#L198

**Comment by kruedger** [comment]
https://github.com/lochmueller/static_info_tables_zh/blob/3045aab8172c881a2d5c4023e19af7eb7888750c/ext_tables_static%2Badt.sql#L146 this line begins with >
https://github.com/lochmueller/static_info_tables_zh/blob/3045aab8172c881a2d5c4023e19af7eb7888750c/ext_tables_static%2Badt.sql#L120 this line begins with P
And the translation for pitcairn is 皮特凯恩

**Comment by lochmueller** [comment]
Fixed via @kruedger pull request. Thanks.
