### ISSUE TITLE
TYPO3 v10 Compatibility

### ISSUE THREAD

**Issue by flossels** [lochmueller/static_info_tables_zh#8]
Hi Tim,

any chance to get this extension ready for TYPO3 v10?

**Comment by lochmueller** [comment]
I have to check the extension in v10 and run a new release... it is not much work to do, but I have no time currently. Perhaps at the end of the month...
Regards, Tim

**Comment by lochmueller** [comment]
Hey @flossels 
there is a new version now: https://github.com/lochmueller/static_info_tables_zh/releases/tag/6.9.0
Regards,
Tim
